export { default as HomeSlider } from './HomeSlider'
export { default as HomeAbout } from './HomeAbout'
export { default as HomeService } from './HomeService'
export { default as HomeChoosing } from './HomeChoosing'
export { default as HomeBlog } from './HomeBlog'
export { default as HomeContact } from './HomeContact'
